// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmCz1-DAFqWGnoqd6KQopxKvWsC0KUOyw',
    appId: '1:455879976470:web:7a0133d908bd852fde7737',
    messagingSenderId: '455879976470',
    projectId: 'flutterfirebase-95bfe',
    authDomain: 'flutterfirebase-95bfe.firebaseapp.com',
    storageBucket: 'flutterfirebase-95bfe.firebasestorage.app',
    measurementId: 'G-EKFWXZ3YDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbYgLf9uNaipzOBuMrOQf8OafmTdtD28',
    appId: '1:455879976470:android:febf414f5e8b6de5de7737',
    messagingSenderId: '455879976470',
    projectId: 'flutterfirebase-95bfe',
    storageBucket: 'flutterfirebase-95bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXfVlKbYQt5a-9q1s08wydWu4vDbjeHpc',
    appId: '1:455879976470:ios:400d9a8a6f6b9e6ade7737',
    messagingSenderId: '455879976470',
    projectId: 'flutterfirebase-95bfe',
    storageBucket: 'flutterfirebase-95bfe.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXfVlKbYQt5a-9q1s08wydWu4vDbjeHpc',
    appId: '1:455879976470:ios:400d9a8a6f6b9e6ade7737',
    messagingSenderId: '455879976470',
    projectId: 'flutterfirebase-95bfe',
    storageBucket: 'flutterfirebase-95bfe.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmCz1-DAFqWGnoqd6KQopxKvWsC0KUOyw',
    appId: '1:455879976470:web:879cab6827e1edc8de7737',
    messagingSenderId: '455879976470',
    projectId: 'flutterfirebase-95bfe',
    authDomain: 'flutterfirebase-95bfe.firebaseapp.com',
    storageBucket: 'flutterfirebase-95bfe.firebasestorage.app',
    measurementId: 'G-99Y8K9KWDS',
  );
}